nutrivale/nutrivale/urls.py
from django.contrib import admin
from django.urls import path
from ingresos.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', menu, name='menu'),

    path('menu_paciente/', vista_paciente, name='menu_paciente'),
    path('menu_paciente/<int:ano>&<int:mes>&<int:dia>', vista_paciente, name='menu_paciente'),
    
    path('agenda/', agenda, name='agenda'),
    path('agenda/<int:ano>&<int:mes>', agenda, name='agenda'),

    path('listado_consulta/', menu_consulta, name='listado_consulta'),
    path('ingreso_consulta/', ingreso_consulta, name='ingreso_consulta'),
    path('eliminar_consulta/<int:id>', eliminar_consulta, name='eliminar_consulta'),
    path('datos_paciente/', datos_paciente, name='datos_paciente'),

    path('pacientes/', menu_paciente, name="pacientes"),
    path('ingreso_paciente/', ingreso_paciente, name='ingreso_paciente'),
    path('eliminar_paciente/<int:id>', eliminar_paciente, name="eliminar_paciente")
]

nutrivale/ingresos/models.py
from django.db import models

# Create your models here.

MODALIDAD = (
    ("ONLINE", "Online"),
    ("PRESENCIAL", "Presencial")
)

ESTADO_CONSULTA = (
    ("ANULADA", "Anulada"),
    ("REALIZADA", "Realizada"),
    ("PENDIENTE", "Pendiente")
)

DIAGNOSTICO = (
    ("ENFLAQUECIDO", "Enflaquecido"),
    ("NORMAL", "Normal"),
    ("SOBREPESO", "Sobrepeso"),
    ("OBESIDAD GRADO I", "Obesidad grado I"),
    ("OBESIDAD GRADO II", "Obesidad grado II")
)

TIPO_CONSULTA =(
    ("INGRESO", "Ingreso"),
    ("CONTROL", "Control")
)
HOURS = (
    ("10:00", "10:00"),
    ("11:00", "11:00"),
    ("12:00", "12:00"),
    ("13:00", "13:00"),
    ("14:00", "14:00"),
    ("15:00", "15:00"),
    ("16:00", "16:00")
)      

class Paciente(models.Model):
    nombre = models.CharField(max_length=100, verbose_name="Nombre")
    apellido = models.CharField(max_length=100, verbose_name="Apellido")
    rut = models.CharField(max_length=20, verbose_name="RUT")
    patologias = models.CharField(max_length=150, verbose_name="Patologías", blank=True)
    active = models.BooleanField()

    def __str__(self):
        return f'{self.nombre} {self.apellido}'

class DatosPaciente(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, verbose_name="Paciente")
    diagnostico = models.CharField(max_length=100, choices=DIAGNOSTICO, verbose_name="Diagnóstico nutricional")
    peso = models.PositiveIntegerField()
    talla = models.PositiveIntegerField()
    imc = models.PositiveIntegerField()
    active = models.BooleanField()

class Consulta(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, verbose_name="Paciente", limit_choices_to={'active': True})
    fecha = models.DateField(verbose_name="Fecha consulta")
    hora = models.CharField(max_length=11, choices=HOURS, verbose_name="Hora", unique_for_date="fecha", 
    error_messages= {'unique_for_date': "La hora no está disponible"}
    )
    
    tipo = models.CharField(max_length=100, choices=TIPO_CONSULTA,verbose_name="Tipo consulta")
    modalidad = models.CharField(max_length=20, choices=MODALIDAD, verbose_name="Modalidad")
    estado = models.CharField(max_length=100, choices=ESTADO_CONSULTA, verbose_name="Estado")
    active = models.BooleanField()

    def __str__(self):
        return f'{self.paciente}'



    

nutrivale/templates/agenda.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="container">
        <div class="row">
            <div class="col">
                <a href="{% url 'agenda' ano=mes_anterior.year mes=mes_anterior.month%}" id="mes_anterior"><img src="{% static 'img/caret-left-fill.svg' %}" alt=""></a>
            </div>
            <div class="col text-center">
                <h1 id="nombre_mes">{{ nombre_mes }} {{ ano_mes }}</h1>
            </div>
            <div class="col">
                <a href="{% url 'agenda' ano=mes_siguiente.year mes=mes_siguiente.month%}" class="float-end" id="mes_siguiente"><img src="{% static 'img/caret-right-fill.svg' %}" alt=""></a>
            </div>
        </div>
    </div>
    <table class="table table-bordered calendario" id="tabla_calendario">
        <thead>
            <tr>
                <th width="150">LU</th>
                <th width="150">MA</th>
                <th width="150">MI</th>
                <th width="150">JU</th>
                <th width="150">VI</th>
                <th width="150">SA</th>
                <th width="150">DO</th>
            </tr>    
        </thead>
        <tbody style="margin:15px;">
            {% for mod in mods %}
            {% if mod.tipo == 'start' %}
            <tr height="120">
            {% endif %}
            <td class="day" 
            {% if mod.tipo == 'end' %}style="color: red; background-color: #ffeeee"{% endif %}
            {% if mod.fecha.day and mod.tipo != 'end' %} data-bs-toggle="modal" data-bs-target="#addItemModal" onclick="setFecha({{mod.fecha.year}}, {{mod.fecha.month}}, {{mod.fecha.day}});setHoras({{mod.horas}});"{% endif %}>
            {{ mod.fecha.day }}
            <br>
                {% for consulta in mod.consultas %}
                <div class="badge text-bg-primary" onclick="setIdDelete({{consulta.id}}, '{{consulta}} {{consulta.hora}} {{consulta.modalidad}} {{consulta.tipo}}', '')" data-bs-toggle="modal" data-bs-target="#deleteItemModal">{{ consulta }}</div>
                {% endfor %}
            </td>
            {% if mod.tipo == 'end' %}
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <!-- Modal Ingresar Item -->
<div class="modal fade" id="addItemModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Ingresar Consulta</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form id="itemForm" method="POST">
                <table class="table">
                    <tbody>
                        {% for field in form %}
                        {% if field == form.active %}
                            {{ field }}
                        {% else %}
                        <tr>
                            <th>{{ field.label_tag }}</th>
                            <td>{{ field }}</td>
                            <td>{{ field.errors }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                    {% csrf_token %}
                </table>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" form="itemForm" class="btn btn-primary">Ingresar</button>
        </div>
      </div>
    </div>
</div>

<!-- Modal eliminar dato -->
<div class="modal fade" id="deleteItemModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Consulta</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p id="datoEliminado"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <a id="deleteConfirm" href="" class="btn btn-danger">Eliminar</a>
        </div>
      </div>
    </div>
</div>

</div>





{% endblock body %}

nutrivale/templates/calendario.html
<div class="dropdown">
    <input type="select" name="fecha" class="form-control dropdown-toggle" required id="id_fecha" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
    <div class="dropdown-menu calendario">
        <div class= "list-group list-group-horizontal">
            <li class="list-group-item border-0">LU</li>
            <li class="list-group-item border-0">MA</li>
            <li class="list-group-item border-0">MI</li>
            <li class="list-group-item border-0">JU</li>
            <li class="list-group-item border-0">VI</li>
            <li class="list-group-item border-0">SA</li>
            <li class="list-group-item border-0">DO</li>
        </div>
        <hr>
        <div style="margin:15px;">
            {% for day, opcion in mods %}
            {% if opcion == 'start' %}
            <div class="row">
            {% endif %}
            <div class="col text-center day " id="dia_{{ day }}">{{ day }}</div>
            {% if opcion == 'end' %}
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div> 
</div>

nutrivale/templates/footer.html
{% load static %}
<footer style="background-color: #BC7DBE; color: #fff;">
    <div class="row py-3 me-0">
        <div class="col-3 mx-auto">
            <h1>nutrivale</h1>
        </div>
        <div class="col-3 mx-auto">
            <h3 class="fw-bold">Contacto</h3>
            <div class="row">
                <div class="col p-1">
                    <a href="">
                        <svg class="social-media-ico" xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                            <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
                        </svg>
                    </a>
                </div>
                <div class="col p-1">
                    <a href="">
                        <svg class="social-media-ico" xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                        </svg>
                    </a>
                </div>
                
                <div class="col p-1">
                    <a href="">
                        <svg class="social-media-ico" xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                        </svg>
                    </a>
                </div>
                <div class="col w-100 m-4">
                    <a class="link-blanco" href=""><h4><i class="bi bi-envelope-fill"></i> nutrivaleparram@gmail.com</h4></a>
                </div>
            </div>
        </div>
        <div class="col-3 mx-auto">
            <h3 class="fw-bold">Ubicación</h3>
            <h5>Eleuterio Ramírez 210, oficina 201, pitrufquén.</p>
        </div>
    </div>
    <div class="text-center" style="background-color: #675E73; margin-bottom: -16px">
        <i class="bi bi-c-circle"></i> Todos los derechos reservados -  Sitio web por José Velásquez</p>
    </div>
</footer>

nutrivale/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="{% static 'js/functions.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/calendario.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% include 'navbar.html' %}
{% block body %}

{% endblock body %}
</body>
</html>

nutrivale/templates/menu.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="container block-container">
        <div class="card border-0" style="max-width: 1300px">
            <div class="row g-0">
              <div class="col-md-6">
                <div class="card-body">
                  <h5 class="card-title morado">¡Come sin culpas!</h5>
                  <p class="card-text">Consulta presencial en Pitrufquén, Araucanía, Chile.</p>
                  <a class="btn btn-morado fw-bold" href="" role="button">Consulta Presencial</a>
                  <a class="btn btn-morado fw-bold" href="" role="button">Consulta Online</a>
                </div>
              </div>
              <div class="col-md-6">
                <img src="{% static 'img/nutri.jpg' %}" class="img-fluid rounded-5" alt="...">
              </div>
            </div>
          </div>
    </div>

    <div class="container block-container">
        <h1 class="text-center morado fw-bold ">ATENCIÓN NUTRICIONAL</h1>
        <div class="row justify-content-between gap-3 m-5">
            <div class="card text-center mx-5 border-0 background-celeste col-md-auto" style="width: 20rem; height: 18rem">
                <div class="card-body">
                  <h5 class="card-title morado">Presencial</h5>
                  <p class="card-text morado">En Av. siempreviva #742 Pitrufquén.</p>
                  <a href="#" class="btn btn-morado fw-bold" role="button">Más información</a>
                </div>
            </div>
            <div class="card text-center mx-5 border-0 background-celeste col-md-auto" style="width: 20rem">
                <div class="card-body">
                  <h5 class="card-title morado">Online</h5>
                  <p class="card-text morado">A través de videollamada para mayor comodidad</p>
                  <a href="#" class="btn btn-morado fw-bold" role="button">Más información</a>
                </div>
            </div>
        </div>
        <div class="container pb-5 mx-5 morado">
            <p>Dirigido a adultos y adultos mayores que:</p>
            <ul>
                <li>Padecen Diabetes mellitus, resistencia a la insulina, hipertensión arterial, dislipidemias, sobrepeso, obesidad.</li>
                <li>Patologías gastrointestinales (enfermedad celiaca, síndrome de intestino irritable, etc).</li>
                <li>Quieran mejorar sus hábitos alimentarios y estilo de vida.</li>
            </ul>
        </div>
        <div class="container block-container">
            <h1 class="morado fw-bold">Sobre mí</h1>
            <div class="card my-5 py-5 border-0" style="max-width: 1300px">
                <div class="row g-0">
                  <div class="col-md-6">
                    <img src="{% static 'img/nutri.jpg' %}" class="img-fluid rounded-circle" alt="...">
                  </div>
                  <div class="col-md-4 my-auto background-celeste h-25 center rounded-5 rounded-start" style="background-color: #FFE4FE">
                    <div class="card-body">
                      <h5 class="card-title morado">¡Hola!</h5>
                      <p class="card-text plomo">Mi motivación como profesional es ayudarte a sanar tu relación con la comida, brindándote 
                        herramientas para que aprendas a hacer mejores elecciones alimentarias, sin pasar hambre.</p>
                    </div>
                  </div>
                </div>
              </div>
        </div>
        <div class="container block-container">
            <h1 class="fst-italic fw-bold text-center">Formación académica</h1>
            <div class="row row-cols-1 gap-5 my-5 py-5">
                <div class="col">Nutricionista titulada de la Universidad de La Frontera</div>
                <div class="col">Certificación internacional en Psicología de la Alimentación</div>
                <div class="col">Certificación internacional en Gastroenterología</div>
                <div class="col">Certificación en el tratamiento de la obesidad</div>
            </div>
        </div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock body %}

nutrivale/templates/menu_paciente.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

<div>errores{{errors}}</div>

<div class="container">    
    <div class="row">
        <div class="col">
            <a href="
            {% if ano_anterior %}
            {% url 'menu_paciente' ano=ano_anterior mes=mes_anterior dia=dia_anterior %}

            {% elif mes_anterior %}
            {% url 'menu_paciente' ano=ano mes=mes_anterior dia=dia_anterior %}

            {% else %}
            {% url 'menu_paciente' ano=ano mes=mes dia=dia_anterior%}
            {% endif %}
            " id="mes_anterior"><img src="{% static 'img/caret-left-fill.svg' %}" alt=""></a>
        </div>
        <div class="col text-center">
            <h1 id="nombre_mes">{{ fecha }}</h1>
        </div>
        <div class="col">
            <a href="
            {% if ano_siguiente %}
            {% url 'menu_paciente' ano=ano_siguiente mes=mes_siguiente dia=dia_siguiente %}

            {% elif mes_siguiente %}
            {% url 'menu_paciente' ano=ano mes=mes_siguiente dia=dia_siguiente %}

            {% else %}
            {% url 'menu_paciente' ano=ano mes=mes dia=dia_siguiente%}
            {% endif %}"
            class="float-end" id="mes_siguiente"><img src="{% static 'img/caret-right-fill.svg' %}" alt=""></a>
        </div>
    </div>
</div>

<div class="container text-center" style="margin-top:100px">
    <table class="table">
        <thead>
            <tr>
                <th>Lunes</th>
                <th>Martes</th>
                <th>Miercoles</th>
                <th>Jueves</th>
                <th>Viernes</th>
                <th>Sábado</th>
                <th>Domingo</th>
            </tr> 
        </thead>
        <tbody class="text-center">
            <tr height="80">
                {% for dia in semana %}
                <td>
                    {{ dia.dia }}
                    {% for hora in dia.horas %}
                    <div>
                        <button type="button" onclick="setFecha({{dia.ano}}, {{dia.mes}}, {{dia.dia}});setHora('{{ hora }}')" class="btn btn-outline-morado m-1" data-bs-toggle="modal" data-bs-target="#addItemModal">
                            {{ hora }}
                        </button>
                    </div>
                    {% endfor %}
                    
                </td>
                {% endfor %}
            </tr>
        </tbody>
    </table>
</div>

<!-- Modal Ingresar Item -->
<div class="modal fade" id="addItemModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Ingresar Consulta</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form id="itemForm" method="POST" class="needs-validation" novalidate>
                <table class="table">
                    {{ form.as_table }}
                    {% csrf_token %}
                </table>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" form="itemForm" class="btn btn-primary">Ingresar</button>
        </div>
      </div>
    </div>
</div>

{% comment %} <div class="modal fade" id="addItemModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Ingresar Consulta</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form id="itemForm2" method="POST">
                <table class="table">
                    {{ form.as_table }}
                    {% csrf_token %}
                </table>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" form="itemForm" class="btn btn-primary">Ingresar</button>
        </div>
      </div>
    </div>
</div> {% endcomment %}

{% endblock body %}

nutrivale/templates/navbar.html
<header class="d-flex flex-wrap justify-content-center py-4 mb-4 border-bottom" style="background-color: #DCD9F6; padding-right: 200px; padding-left: 200px">
  <a href="{% url 'menu' %}" class="d-flex flex-column align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
    <div class="fs-4 wood-font morado"><strong class="fst-italic">Valentina parra</strong></div>
    <div><strong class="text-uppercase">Nutricionista</strong></div>
  </a>

  <ul class="nav nav-pills align-self-center" style="font-size: 1.5rem; link-color:black">
    <li class="nav-item"><a class="nav-link link-plomo fw-light" href="{% url 'menu' %}">Inicio</a></li>
    <li class="nav-item"><a class="nav-link link-plomo fw-light" href="{% url 'listado_consulta' %}">Consultas</a></li>
    <li class="nav-item"><a class="nav-link link-plomo fw-light" href="{% url 'pacientes' %}">Pacientes</a></li>
    <li class="nav-item"><a class="nav-link link-plomo fw-light" href="{% url 'agenda' %}">Agenda</a></li>
    <li class="nav-item"><a class="btn btn-morado btn-lg" role="button" href="{% url 'menu_paciente' %}">Agenda tu hora</a></li>
  </ul>
</header>